### ISSUE TITLE
如何移植到android 里面去推流

### ISSUE THREAD

**Issue by xieyilong** [akanchi/CSimpleRtmp#1]
这个 如和使用jni 移植到android 里面 结合yasea android 客户端，我想移植过去，可以改进推流的延迟

**Comment by akanchi** [comment]
这个也不能改进推流延迟呀，建议直接用原作者的java版本（yasea也是用的这个）https://github.com/faucamp/SimpleRtmp

**Comment by xieyilong** [comment]
我在yasea 上面 有人说使用 libsimplermtp 改进 ，延迟 可以降低到几百ms，我已经移植到 android jni 但是 握手 失败，无法连接

**Comment by akanchi** [comment]
那应该不是说我这个项目了，本项目只是用于学习rtmp协议的相关流程。延迟有很多因素的，比如编码的参数等。rtmp实际应用中延迟几百ms基本无法达到

**Comment by xieyilong** [comment]
是你这，yasea 目前用的是 java版本，你这个是c版本，socket ，他们说用 c版本的socket 推流发送视频帧数据快很多，现在就是不知道为何 握手失败，我已经通过 jni 调到了你的 bool RtmpClient::connect(const std::string &url)  方法，执行到这里就失败了 if (!(ret = handshake())) {
            // 握手失败
            return ret;
        }

**Comment by akanchi** [comment]
可以单步进去或者加点日志看看。
还有c版本和推流快不快没关系呀。。。

**Comment by xieyilong** [comment]
FrankLove commented on 8 Sep
@begeekmyfriend 好的，现在已经可以了。博主，给你提个建议，数据发送这块不建议用java的原生socket，改成jni调用C语言的tcp效率会大幅提高

**Comment by akanchi** [comment]
我这个项目主要是为了学习rtmp，还有问题没解决呢。。
实际项目建议使用这个库哦，https://github.com/ossrs/srs-librtmp
